// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies ApS";
    extern const char* const UnityCopyright = "(c) 2023 Unity Technologies ApS. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2022.2.4f1";
    extern const char* const UnityVersionDigits = "2022.2.4";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2022;
    extern const UInt32 UnityVersionMajor = 2;
    extern const UInt32 UnityVersionMinor = 4;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2022.2.4f1_8216e0211249";
    extern const char* const UnityVersionUnderHash_Verbose = "2022.2.4f1_8216e0211249";
    extern const char* const UnityVersionUnderHash_WithParens = "2022.2.4f1 (8216e0211249)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 8525536;

    extern const UInt64 UnityVersionDate = 1673983303;
    extern const char* const UnityVersionBranch = "2022.2/staging";
    extern const char* const UnityVersionDisplay = "2022.2.4f1";
    extern const char* const UnityVersionDisplay_Verbose = "2022.2.4f1.112.8537";
    extern const char* const UnityVersionRevision = "8216e0211249";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2022.2.4f1 (8216e0211249)";
    extern const wchar_t* const L_UnityVersion = L"2022.2.4f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies ApS"
    #define UNITY_COPYRIGHT "(c) 2023 Unity Technologies ApS. All rights reserved."
    #define UNITY_VERSION_VER 2022
    #define UNITY_VERSION_MAJ 2
    #define UNITY_VERSION_MIN 4
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2022.2.4f1_8216e0211249"
    #define UNITY_VERSION_PARENS_HASH "2022.2.4f1 (8216e0211249)"
    #define UNITY_VERSION_BLD 8525536
    #define UNITY_VERSION_WIN "2022.2.4.8525536"

#endif // !RC_INVOKED
